### PR TITLE
Added correct image of Moto G Play

### PR DESCRIPTION
**Pull request by suyashbansal**

### CODE REVIEW

**Comment by saleemrashid** [comment]
Can Amazon links be trusted to remain constant?

**Comment by suyashbansal** [comment]
I was skeptic about that too. I uploaded it to my imgur account.

**Comment by saleemrashid** [comment]
Please squash the commits, it'll allow for a cleaner history :smile:

**Comment by suyashbansal** [comment]
I am sorry but I don't know how to squash commits from the web interface. 😅

**Comment by saleemrashid** [comment]
It should be fine, the maintainers will probably squash when merging :)

**Pull request merged**
